In [24]:
# Import required libraries
import sklearn
import pandas as pd
from sklearn import datasets
import numpy as np

In [110]:
data_df = pd.read_csv('C:\\Users\\danglc\\Desktop\\machineLearning\\dataSoccer.csv', index_col='Match_ID')

In [111]:
data_df = data_df[(data_df['homeOdd'] >= 1.77) & (data_df['homeOdd'] <= 1.95)]

In [112]:
data_df

,Match Time,League,Minutes,Home,Away,HomeCorner,AwayCorner,H-Score,A-Score,Home_FH_Score,...,A-DangerA,Home_Shot,Away_Shot,H-OnGoal,A-OnGoal,H-OffGoal,A-OffGoal,homeOdd,awayOdd,drawOdd
Match_ID,,,,,,,,,,,,,,,,,,,,,
18538203,2023-01-15 21:00:00,France-Ligue 1,90.0,Toulouse,Brest,10,5,1,1,0.0,...,38.0,18,15,6.0,5.0,12.0,10.0,1.85,4.20,3.60
18546323,2023-01-15 21:00:00,Italy-Serie A,90.0,Udinese,Bologna,6,4,1,2,1.0,...,40.0,22,17,4.0,4.0,18.0,13.0,1.91,4.20,3.40
18731117,2023-01-15 06:00:00,Brazil-Catarinense 1,90.0,Cambori√∫,Joinville,2,4,0,0,0.0,...,42.0,11,10,2.0,2.0,9.0,8.0,1.91,3.80,3.10
18581534,2023-01-15 07:00:00,Mexico-Liga Premier Serie A,90.0,Lobos ULMX,CD Tulancingo,5,6,2,2,1.0,...,47.0,10,10,7.0,4.0,3.0,6.0,1.91,4.00,3.20
18682585,2023-01-15 13:00:00,Australia-W-League,90.0,Melbourne City W,Melbourne Victory W,7,4,1,1,1.0,...,20.0,10,13,4.0,5.0,6.0,8.0,1.80,3.60,3.60
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18761578,2023-01-29 14:30:00,Hong Kong-First Division,90.0,Shatin,Yuen Long,2,6,3,1,3.0,...,55.0,11,13,7.0,7.0,4.0,6.0,1.80,3.50,4.00
18679699,2023-01-29 17:00:00,Thailand-Thai League 3 - BKK-Perimeter,90.0,Nonthaburi,Thonburi University,11,3,1,3,1.0,...,65.0,11,9,5.0,4.0,6.0,5.0,1.95,3.20,3.50
18717754,2023-01-29 17:30:00,Malta-Premier League,90.0,Balzan,Marsaxlokk,2,3,0,0,0.0,...,20.0,2,3,1.0,2.0,1.0,1.0,1.85,3.40,3.75
18619913,2023-01-29 18:00:00,Spain-Tercera - Group 6,90.0,Torrent,Acero,1,4,2,1,1.0,...,67.0,4,2,2.0,2.0,2.0,0.0,1.80,4.33,3.10
18568774,2023-01-29 18:00:00,Turkey-2. Lig: Beyaz,90.0,Amed SK,≈ûanlƒ±urfaspor,0,0,1,0,1.0,...,0.0,0,0,0.0,0.0,0.0,0.0,1.95,3.40,3.20

In [113]:
data_df['rateAttach'] = data_df['H-Attach']-data_df['A-Attach']
data_df['rateDangerousAttach'] = data_df['H-DangerA']-data_df['A-DangerA']
data_df['rateShot'] = data_df['Home_Shot']-data_df['Away_Shot']
data_df['rateOntarget'] = data_df['H-OnGoal']-data_df['A-OnGoal']
data_df['rateOfftarget'] = data_df['H-OffGoal']-data_df['A-OffGoal']
data_df['rateOddtarget'] = data_df['homeOdd']-data_df['awayOdd']
data_df['rateGoal'] = data_df['H-Score']+data_df['A-Score']

In [114]:
# conditions = [
#     (data_df['H-Score'] > data_df['A-Score']),
#     (data_df['H-Score'] == data_df['A-Score']),
#     (data_df['H-Score'] < data_df['A-Score'])]
# values = ['Home', 'Draw', 'Away']
# data_df['1X2Result'] = np.select(conditions, values)

conditions = [
    (data_df['H-Score'] > data_df['A-Score']),
    (data_df['H-Score'] == data_df['A-Score']),
    (data_df['H-Score'] < data_df['A-Score'])]
values = ['Home', 'Away', 'Away']
data_df['1X2Result'] = np.select(conditions, values)

In [115]:
data_df = data_df[data_df['H-Attach'].notnull()]
data_df = data_df[data_df['homeOdd'].notnull()]

In [100]:
data_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 365 entries, 18538203 to 18568774
Data columns (total 32 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Match Time           365 non-null    object
 1   League               365 non-null    object
 2   Minutes              358 non-null    float64
 3   Home                 365 non-null    object
 4   Away                 365 non-null    object
 5   HomeCorner           365 non-null    object
 6   AwayCorner           365 non-null    object
 7   H-Score              365 non-null    int64
 8   A-Score              365 non-null    int64
 9   Home_FH_Score        352 non-null    float64
 10  Away_FH_Score        352 non-null    float64
 11  H-Attach             365 non-null    float64
 12  A-Attach             365 non-null    float64
 13  H-DangerA            365 non-null    float64
 14  A-DangerA            365 non-null    float64
 15  Home_Shot            365 non-null    int64
 16  Away_Shot            365 non-null    int64
 17  H-OnGoal             365 non-null    float64
 18  A-OnGoal             365 non-null    float64
 19  H-OffGoal            365 non-null    float64
 20  A-OffGoal            365 non-null    float64
 21  homeOdd              365 non-null    float64
 22  awayOdd              365 non-null    float64
 23  drawOdd              365 non-null    float64
 24  rateAttach           365 non-null    float64
 25  rateDangerousAttach  365 non-null    float64
 26  rateShot             365 non-null    int64
 27  rateOntarget         365 non-null    float64
 28  rateOfftarget        365 non-null    float64
 29  rateOddtarget        365 non-null    float64
 30  rateGoal             365 non-null    int64
 31  1X2Result            365 non-null    object
dtypes: float64(19), int64(6), object(7)
memory usage: 94.1+ KB

In [116]:
feature = ['League', 'rateAttach', 'rateDangerousAttach','rateShot','rateOfftarget','homeOdd', 'awayOdd', 'drawOdd']

In [117]:
# x = data_df.loc[:,feature]
x = data_df[feature].values
# y = data_df['1X2Result'].values
y = data_df['rateGoal'].values

In [118]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = ct.fit_transform(x)

In [119]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [120]:
from sklearn.model_selection import train_test_split
x_train, x_valid, y_train, y_valid = train_test_split(x,y, train_size=0.8, test_size=0.2, random_state=0)

In [ ]:
# from sklearn.tree import DecisionTreeClassifier
# dt_model = DecisionTreeClassifier(random_state=1)

In [ ]:
# dt_model.fit(x_train, y_train)

In [ ]:
# y_preds = dt_model.predict(x_valid)

In [ ]:
# pd.DataFrame({"Real": y_valid, "Preds": y_preds}).head(30)

In [2]:
# # Load the iris dataset from sklearn
# iris_clf = datasets.load_iris()
# print(iris_clf.target_names)
# print(iris_clf.feature_names)

['setosa' 'versicolor' 'virginica']
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

In [4]:
# # Dividing the datasets into training datasets and test datasets
# X, y = datasets.load_iris( return_X_y = True)
# from sklearn.model_selection import train_test_split

# # 60 % training dataset and 40 % test datasets
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.40)

In [121]:
# Import random forest classifier from sklearn assemble module
from sklearn.ensemble import RandomForestRegressor

In [6]:
# # Create dataframe
# data = pd.DataFrame({'sepallength': iris_clf.data[:, 0],
# 'sepalwidth': iris_clf.data[:, 1],
# 'petallength': iris_clf.data[:, 2],
# 'petalwidth': iris_clf.data[:, 3],
# 'species': iris_clf.target})

In [11]:
# data

     sepallength  sepalwidth  petallength  petalwidth  species
0            5.1         3.5          1.4         0.2        0
1            4.9         3.0          1.4         0.2        0
2            4.7         3.2          1.3         0.2        0
3            4.6         3.1          1.5         0.2        0
4            5.0         3.6          1.4         0.2        0
..           ...         ...          ...         ...      ...
145          6.7         3.0          5.2         2.3        2
146          6.3         2.5          5.0         1.9        2
147          6.5         3.0          5.2         2.0        2
148          6.2         3.4          5.4         2.3        2
149          5.9         3.0          5.1         1.8        2

[150 rows x 5 columns]

In [122]:
# Create a Random Forest classifier
RForest_clf = RandomForestRegressor()

In [123]:
# Train the model on the training dataset by using fit() function
RForest_clf.fit(x_train, y_train)

RandomForestRegressor()

In [124]:
# Predict from the test dataset
y_preds = RForest_clf.predict(x_valid)

In [131]:
y_preds

array([2.33, 1.94, 2.  , 2.21, 2.1 , 1.98, 2.58, 2.49, 1.62, 2.51, 2.01,
       2.37, 1.74, 2.01, 2.  , 1.55, 4.34, 1.95, 2.48, 1.88, 1.38, 2.79,
       2.73, 2.88, 1.57, 2.68, 2.08, 2.38, 1.9 , 2.28, 2.24, 1.49, 2.31,
       2.11, 3.27, 1.23, 1.87, 1.76, 2.82, 2.19, 1.87, 1.78, 2.79, 3.15,
       2.94, 2.06, 2.33, 1.36, 1.91, 2.42, 3.28, 2.38, 2.83, 2.53, 2.61,
       2.12, 1.74, 1.51, 2.24, 1.95, 2.29, 1.57, 3.05, 1.98, 3.01, 3.04,
       2.05, 2.77, 3.06, 3.12, 2.46, 1.75, 3.52])

In [135]:
# # Create dataframe
data = pd.DataFrame({'y_preds': y_preds,
'Real': y_valid,}
)

# # Import metrics for accuracy calculation
# from sklearn import metrics
# print('\n'"Accuracy of our Random Forst Classifier is: ",
# metrics.accuracy_score(y_valid, y_preds)*100)

In [138]:
data.head(30)

    y_preds  Real
0      2.33     3
1      1.94     3
2      2.00     2
3      2.21     6
4      2.10     2
5      1.98     4
6      2.58     5
7      2.49     3
8      1.62     5
9      2.51     3
10     2.01     0
11     2.37     3
12     1.74     0
13     2.01     2
14     2.00     6
15     1.55     0
16     4.34     1
17     1.95     4
18     2.48     3
19     1.88     6
20     1.38     3
21     2.79     2
22     2.73     6
23     2.88     7
24     1.57     2
25     2.68     7
26     2.08     6
27     2.38     2
28     1.90     5
29     2.28     4